"""
Comprehensive Nepal Administrative Data
========================================
7 Provinces, 77 Districts, 753 Local Levels (Municipalities), ~6743 Wards

Data structure:
    DISTRICTS = [
        {
            "name": str,          # District name
            "province": str,      # Province name
            "lat": float,         # Approximate center latitude
            "lng": float,         # Approximate center longitude
            "zone": str,          # "terai" | "hill" | "mountain"
            "munis": [            # List of municipalities
                (name, type_code, ward_count),
                ...
            ]
        },
    ]

Type codes:
    MC  = Metropolitan City
    SMC = Sub-Metropolitan City
    M   = Municipality
    RM  = Rural Municipality
"""

DISTRICTS = [
    # =========================================================================
    # PROVINCE 1 - KOSHI PRADESH  (14 districts)
    # =========================================================================
    {
        "name": "Taplejung", "province": "Koshi", "lat": 27.35, "lng": 87.67, "zone": "mountain",
        "munis": [
            ("Phungling", "M", 9),
            ("Pathivara Yangwarak", "RM", 7),
            ("Sidingwa", "RM", 6),
            ("Meringden", "RM", 6),
            ("Phaktanglung", "RM", 5),
            ("Mikwakhola", "RM", 6),
            ("Aathrai Triveni", "RM", 6),
            ("Sirijangha", "RM", 6),
            ("Maiwakhola", "RM", 5),
        ],
    },
    {
        "name": "Panchthar", "province": "Koshi", "lat": 27.13, "lng": 87.78, "zone": "hill",
        "munis": [
            ("Phidim", "M", 14),
            ("Hilihang", "RM", 6),
            ("Kummayak", "RM", 6),
            ("Miklajung", "RM", 6),
            ("Falgunanda", "RM", 7),
            ("Tumbewa", "RM", 5),
            ("Yangwarak", "RM", 6),
            ("Phalelung", "RM", 6),
        ],
    },
    {
        "name": "Ilam", "province": "Koshi", "lat": 26.91, "lng": 87.93, "zone": "hill",
        "munis": [
            ("Ilam", "M", 12),
            ("Deumai", "M", 12),
            ("Mai", "M", 12),
            ("Suryodaya", "M", 14),
            ("Sandakpur", "RM", 6),
            ("Fakphokthum", "RM", 7),
            ("Mangsebung", "RM", 6),
            ("Chulachuli", "RM", 6),
            ("Rong", "RM", 6),
            ("Maijogmai", "RM", 6),
        ],
    },
    {
        "name": "Jhapa", "province": "Koshi", "lat": 26.54, "lng": 87.89, "zone": "terai",
        "munis": [
            ("Mechinagar", "M", 15),
            ("Birtamod", "M", 11),
            ("Bhadrapur", "M", 10),
            ("Arjundhara", "M", 11),
            ("Kankai", "M", 10),
            ("Shivasatakshi", "M", 10),
            ("Damak", "M", 10),
            ("Gauradaha", "M", 9),
            ("Buddhashanti", "RM", 6),
            ("Barhadashi", "RM", 5),
            ("Jhapa", "RM", 7),
            ("Haldibari", "RM", 5),
            ("Kachankawal", "RM", 7),
            ("Gaurigunj", "RM", 6),
            ("Kamal", "RM", 8),
        ],
    },
    {
        "name": "Morang", "province": "Koshi", "lat": 26.66, "lng": 87.46, "zone": "terai",
        "munis": [
            ("Biratnagar", "MC", 19),
            ("Sundarharaicha", "M", 13),
            ("Belbari", "M", 12),
            ("Pathari Shanishchare", "M", 10),
            ("Urlabari", "M", 12),
            ("Rangeli", "M", 10),
            ("Letang", "M", 10),
            ("Ratuwamai", "M", 9),
            ("Sunawarshi", "M", 10),
            ("Kerabari", "M", 9),
            ("Kanepokhari", "RM", 7),
            ("Budhiganga", "RM", 7),
            ("Gramthan", "RM", 7),
            ("Katahari", "RM", 7),
            ("Dhanpalthan", "RM", 6),
            ("Jahada", "RM", 6),
            ("Miklajung", "RM", 7),
        ],
    },
    {
        "name": "Sunsari", "province": "Koshi", "lat": 26.65, "lng": 87.17, "zone": "terai",
        "munis": [
            ("Dharan", "SMC", 20),
            ("Itahari", "SMC", 20),
            ("Inaruwa", "M", 10),
            ("Duhabi", "M", 10),
            ("Ramdhuni", "M", 9),
            ("Barahkshetra", "M", 10),
            ("Koshi", "RM", 7),
            ("Gadhi", "RM", 7),
            ("Barju", "RM", 5),
            ("Bhokraha Narsingh", "RM", 7),
            ("Harinagar", "RM", 5),
            ("Dewanganj", "RM", 6),
        ],
    },
    {
        "name": "Dhankuta", "province": "Koshi", "lat": 26.98, "lng": 87.35, "zone": "hill",
        "munis": [
            ("Dhankuta", "M", 10),
            ("Pakhribas", "M", 12),
            ("Mahalaxmi", "M", 10),
            ("Sahidbhumi", "RM", 7),
            ("Chaubise", "RM", 6),
            ("Sangurigadhi", "RM", 6),
            ("Chhathar Jorpati", "RM", 5),
        ],
    },
    {
        "name": "Terhathum", "province": "Koshi", "lat": 27.08, "lng": 87.55, "zone": "hill",
        "munis": [
            ("Myanglung", "M", 10),
            ("Laligurans", "M", 10),
            ("Aathrai", "M", 9),
            ("Chhathar", "RM", 5),
            ("Phedap", "RM", 6),
            ("Menchayam", "RM", 5),
        ],
    },
    {
        "name": "Sankhuwasabha", "province": "Koshi", "lat": 27.35, "lng": 87.23, "zone": "mountain",
        "munis": [
            ("Khandbari", "M", 12),
            ("Chainpur", "M", 12),
            ("Dharmadevi", "M", 10),
            ("Madi", "M", 10),
            ("Panchkhapan", "M", 10),
            ("Bhotkhola", "RM", 5),
            ("Makalu", "RM", 6),
            ("Chichila", "RM", 5),
            ("Sabhapokhari", "RM", 6),
            ("Silichong", "RM", 5),
        ],
    },
    {
        "name": "Bhojpur", "province": "Koshi", "lat": 27.17, "lng": 87.05, "zone": "hill",
        "munis": [
            ("Bhojpur", "M", 12),
            ("Shadanand", "M", 10),
            ("Tyamke Maiyum", "RM", 6),
            ("Arun", "RM", 7),
            ("Hatuwagadhi", "RM", 8),
            ("Ramprasad Rai", "RM", 5),
            ("Aamchowk", "RM", 5),
            ("Pauwadungma", "RM", 6),
            ("Salpasilichho", "RM", 6),
        ],
    },
    {
        "name": "Solukhumbu", "province": "Koshi", "lat": 27.79, "lng": 86.74, "zone": "mountain",
        "munis": [
            ("Solududhkunda", "M", 11),
            ("Necha Salyan", "RM", 5),
            ("Dudhkoshi", "RM", 5),
            ("Mahakulung", "RM", 6),
            ("Sotang", "RM", 5),
            ("Likhu Pike", "RM", 5),
            ("Khumbu Pasanglhamu", "RM", 5),
            ("Thulung Dudhkoshi", "RM", 6),
        ],
    },
    {
        "name": "Okhaldhunga", "province": "Koshi", "lat": 27.30, "lng": 86.52, "zone": "hill",
        "munis": [
            ("Siddhicharan", "M", 12),
            ("Manebhanjyang", "RM", 6),
            ("Champadevi", "RM", 5),
            ("Sunkoshi", "RM", 7),
            ("Khiji Demba", "RM", 5),
            ("Molung", "RM", 5),
            ("Chisankhugadhi", "RM", 5),
            ("Likhu", "RM", 6),
        ],
    },
    {
        "name": "Khotang", "province": "Koshi", "lat": 27.02, "lng": 86.83, "zone": "hill",
        "munis": [
            ("Diktel Rupakot Majhuwagadhi", "M", 14),
            ("Halesi Tuwachung", "M", 12),
            ("Khotehang", "RM", 5),
            ("Diprung Chuichumma", "RM", 5),
            ("Ainselukharka", "RM", 6),
            ("Jantedhunga", "RM", 5),
            ("Kepilasgadhi", "RM", 5),
            ("Barahapokhari", "RM", 5),
            ("Sakela", "RM", 6),
            ("Rawabesi", "RM", 5),
        ],
    },
    {
        "name": "Udayapur", "province": "Koshi", "lat": 26.93, "lng": 86.50, "zone": "hill",
        "munis": [
            ("Triyuga", "M", 14),
            ("Katari", "M", 11),
            ("Chaudandigadhi", "M", 10),
            ("Belaka", "M", 9),
            ("Rautamai", "RM", 5),
            ("Udayapurgadhi", "RM", 7),
            ("Tapli", "RM", 5),
            ("Limchungbung", "RM", 5),
        ],
    },

    # =========================================================================
    # PROVINCE 2 - MADHESH PRADESH  (8 districts)
    # =========================================================================
    {
        "name": "Saptari", "province": "Madhesh", "lat": 26.57, "lng": 86.74, "zone": "terai",
        "munis": [
            ("Rajbiraj", "M", 15),
            ("Kanchanrup", "M", 10),
            ("Dakneshwori", "M", 10),
            ("Saptakoshi", "M", 9),
            ("Bodebarsain", "M", 9),
            ("Shambhunath", "M", 10),
            ("Surunga", "M", 10),
            ("Hanumannagar Kankalini", "M", 10),
            ("Khadak", "M", 6),
            ("Agnisair Krishna Savaran", "RM", 6),
            ("Rajgadh", "RM", 6),
            ("Rupani", "RM", 6),
            ("Tilathi Koiladi", "RM", 8),
            ("Tirhut", "RM", 7),
            ("Bishnupur", "RM", 6),
            ("Mahadeva", "RM", 6),
            ("Balan Bihul", "RM", 5),
        ],
    },
    {
        "name": "Siraha", "province": "Madhesh", "lat": 26.65, "lng": 86.20, "zone": "terai",
        "munis": [
            ("Siraha", "M", 22),
            ("Lahan", "M", 15),
            ("Mirchaiya", "M", 13),
            ("Golbazar", "M", 11),
            ("Dhangadhimai", "M", 10),
            ("Kalyanpur", "M", 9),
            ("Karjanha", "M", 9),
            ("Sukhipur", "M", 9),
            ("Bhagawanpur", "RM", 7),
            ("Aurahi", "RM", 7),
            ("Bishnupur", "RM", 5),
            ("Bariyarpatti", "RM", 5),
            ("Lakshmipur Patari", "RM", 7),
            ("Naraha", "RM", 6),
            ("Sakhuwanankar Katti", "RM", 6),
            ("Arnama", "RM", 5),
            ("Navarajpur", "RM", 5),
        ],
    },
    {
        "name": "Dhanusha", "province": "Madhesh", "lat": 26.76, "lng": 85.93, "zone": "terai",
        "munis": [
            ("Janakpurdham", "SMC", 25),
            ("Chhireshwornath", "M", 10),
            ("Ganeshman Charnath", "M", 10),
            ("Dhanusadham", "M", 9),
            ("Nagarain", "M", 9),
            ("Bideha", "M", 9),
            ("Mithila", "M", 11),
            ("Sahidnagar", "M", 9),
            ("Sabaila", "M", 10),
            ("Kamala", "M", 10),
            ("Mithila Bihari", "M", 9),
            ("Hansapur", "M", 9),
            ("Janaknandani", "RM", 7),
            ("Bateshwar", "RM", 6),
            ("Mukhiyapatti Musaharmiya", "RM", 7),
            ("Lakshminiya", "RM", 6),
            ("Aaurahi", "RM", 7),
            ("Dhanauji", "RM", 7),
        ],
    },
    {
        "name": "Mahottari", "province": "Madhesh", "lat": 26.76, "lng": 85.77, "zone": "terai",
        "munis": [
            ("Jaleshwar", "M", 14),
            ("Bardibas", "M", 13),
            ("Gaushala", "M", 13),
            ("Loharpatti", "M", 9),
            ("Ramgopalpur", "M", 9),
            ("Aurahi", "M", 9),
            ("Balwa", "M", 10),
            ("Manara Siswa", "M", 9),
            ("Matihani", "M", 10),
            ("Bhangaha", "M", 9),
            ("Ekdanra", "RM", 5),
            ("Pipra", "RM", 5),
            ("Samsi", "RM", 5),
            ("Sonama", "RM", 5),
            ("Mahottari", "RM", 6),
        ],
    },
    {
        "name": "Sarlahi", "province": "Madhesh", "lat": 26.87, "lng": 85.56, "zone": "terai",
        "munis": [
            ("Malangwa", "M", 15),
            ("Ishworpur", "M", 10),
            ("Haripur", "M", 9),
            ("Lalbandi", "M", 12),
            ("Barahathawa", "M", 11),
            ("Godaita", "M", 9),
            ("Balara", "M", 9),
            ("Hariwan", "M", 11),
            ("Haripurwa", "M", 10),
            ("Kabilasi", "M", 10),
            ("Bagmati", "M", 10),
            ("Chandranagar", "RM", 5),
            ("Dhankaul", "RM", 5),
            ("Parsa", "RM", 5),
            ("Bishnu", "RM", 6),
            ("Ramnagar", "RM", 6),
            ("Kaudena", "RM", 5),
            ("Chakraghatta", "RM", 5),
            ("Bramhapuri", "RM", 5),
            ("Basbariya", "RM", 5),
        ],
    },
    {
        "name": "Rautahat", "province": "Madhesh", "lat": 27.00, "lng": 85.30, "zone": "terai",
        "munis": [
            ("Gaur", "M", 13),
            ("Chandrapur", "M", 12),
            ("Garuda", "M", 9),
            ("Gujara", "M", 9),
            ("Brindaban", "M", 10),
            ("Ishanath", "M", 10),
            ("Katahariya", "M", 9),
            ("Maulapur", "M", 9),
            ("Madhav Narayan", "M", 9),
            ("Gadhimai", "M", 10),
            ("Baudhimai", "M", 9),
            ("Dewahi Gonahi", "M", 9),
            ("Paroha", "M", 9),
            ("Phatuwa Bijayapur", "M", 9),
            ("Rajpur", "M", 9),
            ("Rajdevi", "M", 9),
            ("Durga Bhagwati", "RM", 5),
            ("Yamunamai", "RM", 5),
        ],
    },
    {
        "name": "Bara", "province": "Madhesh", "lat": 27.07, "lng": 85.07, "zone": "terai",
        "munis": [
            ("Kalaiya", "SMC", 22),
            ("Jeetpur Simara", "SMC", 22),
            ("Kolhabi", "M", 11),
            ("Nijgadh", "M", 13),
            ("Mahagadhimai", "M", 10),
            ("Simraungadh", "M", 11),
            ("Pacharauta", "M", 9),
            ("Pheta", "M", 9),
            ("Bishrampur", "M", 9),
            ("Prasauni", "M", 9),
            ("Adarsha Kotwal", "RM", 5),
            ("Karaiyamai", "RM", 5),
            ("Devtal", "RM", 5),
            ("Parwanipur", "RM", 5),
            ("Baragadhi", "RM", 5),
            ("Suwarna", "RM", 5),
        ],
    },
    {
        "name": "Parsa", "province": "Madhesh", "lat": 27.13, "lng": 84.87, "zone": "terai",
        "munis": [
            ("Birgunj", "MC", 32),
            ("Pokhariya", "M", 11),
            ("Bahudarmai", "M", 9),
            ("Parsagadhi", "M", 11),
            ("Sakhuwa Prasauni", "M", 9),
            ("Jagarnathpur", "M", 9),
            ("Dhobini", "M", 9),
            ("Chhipaharmai", "M", 9),
            ("Bindabasini", "M", 9),
            ("Pakaha Mainpur", "RM", 5),
            ("Thori", "RM", 5),
            ("Jagai", "RM", 7),
            ("Kalikamai", "RM", 5),
            ("Paterwa Sugauli", "RM", 5),
        ],
    },

    # =========================================================================
    # PROVINCE 3 - BAGMATI PRADESH  (13 districts)
    # =========================================================================
    {
        "name": "Dolakha", "province": "Bagmati", "lat": 27.65, "lng": 86.07, "zone": "mountain",
        "munis": [
            ("Bhimeshwar", "M", 9),
            ("Jiri", "M", 9),
            ("Kalinchowk", "RM", 7),
            ("Melung", "RM", 6),
            ("Bigu", "RM", 7),
            ("Gaurishankar", "RM", 9),
            ("Baiteshwar", "RM", 5),
            ("Sailung", "RM", 5),
            ("Tamakoshi", "RM", 7),
        ],
    },
    {
        "name": "Sindhupalchok", "province": "Bagmati", "lat": 27.95, "lng": 85.68, "zone": "mountain",
        "munis": [
            ("Chautara Sangachokgadhi", "M", 12),
            ("Barhabise", "M", 9),
            ("Melamchi", "M", 13),
            ("Bahrabise", "M", 9),
            ("Panchpokhari Thangpal", "RM", 7),
            ("Jugal", "RM", 5),
            ("Balefi", "RM", 5),
            ("Helambu", "RM", 7),
            ("Indrawati", "RM", 8),
            ("Tripurasundari", "RM", 6),
            ("Lisankhu Pakhar", "RM", 5),
            ("Sunkoshi", "RM", 5),
        ],
    },
    {
        "name": "Rasuwa", "province": "Bagmati", "lat": 28.08, "lng": 85.28, "zone": "mountain",
        "munis": [
            ("Uttargaya", "RM", 7),
            ("Kalika", "RM", 5),
            ("Gosaikunda", "RM", 7),
            ("Naukunda", "RM", 5),
            ("Aamachhodingmo", "RM", 6),
        ],
    },
    {
        "name": "Dhading", "province": "Bagmati", "lat": 27.87, "lng": 84.93, "zone": "hill",
        "munis": [
            ("Dhunibeshi", "M", 9),
            ("Nilkantha", "M", 14),
            ("Benighat Rorang", "RM", 9),
            ("Gajuri", "RM", 7),
            ("Galchi", "RM", 7),
            ("Gangajamuna", "RM", 7),
            ("Jwalamukhi", "RM", 5),
            ("Khaniyabas", "RM", 7),
            ("Netrawati Dabjong", "RM", 5),
            ("Rubi Valley", "RM", 5),
            ("Siddhalek", "RM", 7),
            ("Thakre", "RM", 9),
            ("Tripurasundari", "RM", 5),
        ],
    },
    {
        "name": "Nuwakot", "province": "Bagmati", "lat": 27.91, "lng": 85.16, "zone": "hill",
        "munis": [
            ("Bidur", "M", 13),
            ("Belkotgadhi", "M", 13),
            ("Kakani", "RM", 7),
            ("Dupcheshwar", "RM", 5),
            ("Shivapuri", "RM", 7),
            ("Kispang", "RM", 5),
            ("Myagang", "RM", 5),
            ("Tadi", "RM", 6),
            ("Likhu", "RM", 5),
            ("Suryagadhi", "RM", 5),
            ("Tarkeshwar", "RM", 5),
            ("Panchakanya", "RM", 5),
        ],
    },
    {
        "name": "Kathmandu", "province": "Bagmati", "lat": 27.71, "lng": 85.32, "zone": "hill",
        "munis": [
            ("Kathmandu", "MC", 32),
            ("Kageshwori Manohara", "M", 9),
            ("Kirtipur", "M", 10),
            ("Gokarneshwor", "M", 9),
            ("Chandragiri", "M", 15),
            ("Tokha", "M", 11),
            ("Tarkeshwar", "M", 11),
            ("Nagarjun", "M", 10),
            ("Budhanilkantha", "M", 13),
            ("Tarakeshwar", "M", 11),
            ("Dakshinkali", "M", 9),
            ("Shankharapur", "M", 9),
        ],
    },
    {
        "name": "Bhaktapur", "province": "Bagmati", "lat": 27.67, "lng": 85.43, "zone": "hill",
        "munis": [
            ("Bhaktapur", "M", 10),
            ("Madhyapur Thimi", "M", 9),
            ("Suryabinayak", "M", 10),
            ("Changunarayan", "M", 9),
        ],
    },
    {
        "name": "Lalitpur", "province": "Bagmati", "lat": 27.65, "lng": 85.33, "zone": "hill",
        "munis": [
            ("Lalitpur", "MC", 29),
            ("Godawari", "M", 14),
            ("Mahalaxmi", "M", 10),
            ("Konjyosom", "RM", 5),
            ("Bagmati", "RM", 7),
            ("Mahankal", "RM", 6),
        ],
    },
    {
        "name": "Kavrepalanchok", "province": "Bagmati", "lat": 27.53, "lng": 85.57, "zone": "hill",
        "munis": [
            ("Dhulikhel", "M", 12),
            ("Banepa", "M", 14),
            ("Panauti", "M", 12),
            ("Panchkhal", "M", 10),
            ("Namobuddha", "M", 11),
            ("Mandandeupur", "M", 12),
            ("Khanikhola", "RM", 5),
            ("Chauri Deurali", "RM", 5),
            ("Temal", "RM", 8),
            ("Bethanchowk", "RM", 7),
            ("Bhumlu", "RM", 7),
            ("Mahabharat", "RM", 7),
            ("Roshi", "RM", 8),
        ],
    },
    {
        "name": "Ramechhap", "province": "Bagmati", "lat": 27.32, "lng": 86.13, "zone": "hill",
        "munis": [
            ("Manthali", "M", 14),
            ("Ramechhap", "M", 10),
            ("Umakunda", "RM", 5),
            ("Khandadevi", "RM", 6),
            ("Gokulganga", "RM", 7),
            ("Doramba", "RM", 5),
            ("Sunapati", "RM", 5),
            ("Likhu Tamakoshi", "RM", 5),
        ],
    },
    {
        "name": "Sindhuli", "province": "Bagmati", "lat": 27.25, "lng": 85.97, "zone": "hill",
        "munis": [
            ("Kamalamai", "M", 14),
            ("Dudhauli", "M", 12),
            ("Sunkoshi", "RM", 5),
            ("Golanjor", "RM", 7),
            ("Phikkal", "RM", 5),
            ("Tinpatan", "RM", 6),
            ("Marin", "RM", 5),
            ("Ghyanglekh", "RM", 5),
            ("Hariharpurgadhi", "RM", 6),
        ],
    },
    {
        "name": "Makwanpur", "province": "Bagmati", "lat": 27.42, "lng": 85.04, "zone": "hill",
        "munis": [
            ("Hetauda", "SMC", 20),
            ("Thaha", "M", 12),
            ("Bhimphedi", "RM", 9),
            ("Makwanpurgadhi", "RM", 9),
            ("Manahari", "RM", 7),
            ("Raksirang", "RM", 9),
            ("Bakaiya", "RM", 9),
            ("Bagmati", "RM", 9),
            ("Kailash", "RM", 7),
            ("Indrasarowar", "RM", 7),
        ],
    },
    {
        "name": "Chitwan", "province": "Bagmati", "lat": 27.53, "lng": 84.36, "zone": "terai",
        "munis": [
            ("Bharatpur", "MC", 29),
            ("Ratnanagar", "M", 16),
            ("Khairahani", "M", 13),
            ("Kalika", "M", 11),
            ("Rapti", "M", 13),
            ("Ichchhakamana", "RM", 6),
            ("Madi", "M", 10),
        ],
    },

    # =========================================================================
    # PROVINCE 4 - GANDAKI PRADESH  (11 districts)
    # =========================================================================
    {
        "name": "Gorkha", "province": "Gandaki", "lat": 28.00, "lng": 84.63, "zone": "hill",
        "munis": [
            ("Gorkha", "M", 14),
            ("Palungtar", "M", 10),
            ("Sulikot", "RM", 6),
            ("Siranchowk", "RM", 6),
            ("Ajirkot", "RM", 5),
            ("Aarughat", "RM", 5),
            ("Gandaki", "RM", 6),
            ("Dharche", "RM", 5),
            ("Bhimsen Thapa", "RM", 5),
            ("Shahid Lakhan", "RM", 5),
            ("Chum Nubri", "RM", 7),
        ],
    },
    {
        "name": "Lamjung", "province": "Gandaki", "lat": 28.27, "lng": 84.41, "zone": "hill",
        "munis": [
            ("Besisahar", "M", 11),
            ("Sundarbazar", "M", 11),
            ("Rainas", "M", 9),
            ("Madhya Nepal", "M", 9),
            ("Dordi", "RM", 6),
            ("Dudhpokhari", "RM", 6),
            ("Marsyangdi", "RM", 7),
            ("Kwholasothar", "RM", 5),
        ],
    },
    {
        "name": "Tanahun", "province": "Gandaki", "lat": 27.92, "lng": 84.23, "zone": "hill",
        "munis": [
            ("Damauli", "M", 14),
            ("Byas", "M", 14),
            ("Shuklagandaki", "M", 11),
            ("Bhanu", "M", 13),
            ("Bandipur", "RM", 7),
            ("Rishing", "RM", 7),
            ("Ghiring", "RM", 6),
            ("Devghat", "RM", 7),
            ("Myagde", "RM", 6),
            ("Aanbu Khaireni", "RM", 9),
        ],
    },
    {
        "name": "Syangja", "province": "Gandaki", "lat": 28.09, "lng": 83.87, "zone": "hill",
        "munis": [
            ("Putalibazar", "M", 14),
            ("Galyang", "M", 11),
            ("Chapakot", "M", 9),
            ("Bhirkot", "M", 9),
            ("Waling", "M", 14),
            ("Arjun Chaupari", "RM", 7),
            ("Aandhikhola", "RM", 5),
            ("Kaligandaki", "RM", 5),
            ("Phedikhola", "RM", 5),
            ("Harinas", "RM", 6),
            ("Biruwa", "RM", 6),
        ],
    },
    {
        "name": "Kaski", "province": "Gandaki", "lat": 28.22, "lng": 83.99, "zone": "hill",
        "munis": [
            ("Pokhara", "MC", 33),
            ("Annapurna", "RM", 11),
            ("Machhapuchchhre", "RM", 9),
            ("Madi", "RM", 9),
            ("Rupa", "RM", 7),
        ],
    },
    {
        "name": "Manang", "province": "Gandaki", "lat": 28.67, "lng": 84.02, "zone": "mountain",
        "munis": [
            ("Chame", "RM", 5),
            ("Narpa Bhumi", "RM", 5),
            ("Nasong", "RM", 5),
            ("Manang Ngisyang", "RM", 5),
        ],
    },
    {
        "name": "Mustang", "province": "Gandaki", "lat": 29.18, "lng": 83.76, "zone": "mountain",
        "munis": [
            ("Gharapjhong", "RM", 5),
            ("Thasang", "RM", 5),
            ("Barhagaun Muktichhetra", "RM", 5),
            ("Lo Ghekar Damodarkunda", "RM", 5),
            ("Lomanthang", "RM", 5),
        ],
    },
    {
        "name": "Myagdi", "province": "Gandaki", "lat": 28.47, "lng": 83.52, "zone": "hill",
        "munis": [
            ("Beni", "M", 11),
            ("Annapurna", "RM", 7),
            ("Dhaulagiri", "RM", 5),
            ("Mangala", "RM", 6),
            ("Malika", "RM", 5),
            ("Raghuganga", "RM", 5),
        ],
    },
    {
        "name": "Parbat", "province": "Gandaki", "lat": 28.39, "lng": 83.61, "zone": "hill",
        "munis": [
            ("Kusma", "M", 14),
            ("Phalebas", "M", 10),
            ("Jaljala", "RM", 5),
            ("Modi", "RM", 7),
            ("Mahashila", "RM", 5),
            ("Bihadi", "RM", 5),
            ("Paiyun", "RM", 5),
        ],
    },
    {
        "name": "Baglung", "province": "Gandaki", "lat": 28.27, "lng": 83.59, "zone": "hill",
        "munis": [
            ("Baglung", "M", 14),
            ("Dhorpatan", "M", 9),
            ("Galkot", "M", 10),
            ("Jaimini", "M", 11),
            ("Bareng", "RM", 5),
            ("Kathekhola", "RM", 5),
            ("Taman Khola", "RM", 5),
            ("Tara Khola", "RM", 6),
            ("Nisikhola", "RM", 6),
            ("Badigad", "RM", 7),
        ],
    },
    {
        "name": "Nawalpur", "province": "Gandaki", "lat": 27.72, "lng": 84.11, "zone": "terai",
        "munis": [
            ("Kawasoti", "M", 15),
            ("Gaindakot", "M", 13),
            ("Devchuli", "M", 14),
            ("Madhyabindu", "M", 13),
            ("Hupsekot", "RM", 7),
            ("Binayi Triveni", "RM", 6),
            ("Bulingtar", "RM", 6),
            ("Baudikali", "RM", 5),
        ],
    },

    # =========================================================================
    # PROVINCE 5 - LUMBINI PRADESH  (12 districts)
    # =========================================================================
    {
        "name": "Parasi", "province": "Lumbini", "lat": 27.50, "lng": 83.70, "zone": "terai",
        "munis": [
            ("Bardaghat", "M", 13),
            ("Ramgram", "M", 14),
            ("Sunwal", "M", 12),
            ("Susta", "RM", 6),
            ("Pratappur", "RM", 6),
            ("Sarawal", "RM", 6),
            ("Palhi Nandan", "RM", 7),
        ],
    },
    {
        "name": "Rupandehi", "province": "Lumbini", "lat": 27.50, "lng": 83.44, "zone": "terai",
        "munis": [
            ("Butwal", "SMC", 19),
            ("Siddharthanagar", "M", 13),
            ("Devdaha", "M", 11),
            ("Lumbini Sanskritik", "M", 9),
            ("Sainamaina", "M", 11),
            ("Tillotama", "M", 17),
            ("Rohini", "M", 9),
            ("Marchawari", "RM", 6),
            ("Gaidahawa", "RM", 7),
            ("Omsatiya", "RM", 6),
            ("Siyari", "RM", 6),
            ("Sammarimai", "RM", 6),
            ("Kanchan", "RM", 6),
            ("Suddhodhan", "RM", 6),
            ("Mayadevi", "RM", 6),
            ("Kotahimai", "RM", 5),
        ],
    },
    {
        "name": "Kapilvastu", "province": "Lumbini", "lat": 27.57, "lng": 83.05, "zone": "terai",
        "munis": [
            ("Kapilvastu", "M", 12),
            ("Buddhabhumi", "M", 10),
            ("Shivaraj", "M", 12),
            ("Maharajgunj", "M", 9),
            ("Banganga", "M", 11),
            ("Krishnanagar", "M", 10),
            ("Mayadevi", "RM", 5),
            ("Yasodhara", "RM", 6),
            ("Suddhodhan", "RM", 5),
            ("Bijaynagar", "RM", 7),
        ],
    },
    {
        "name": "Arghakhanchi", "province": "Lumbini", "lat": 28.05, "lng": 83.15, "zone": "hill",
        "munis": [
            ("Sandhikharka", "M", 12),
            ("Sitganga", "M", 12),
            ("Bhumikasthan", "M", 11),
            ("Chhatradev", "RM", 5),
            ("Panini", "RM", 5),
            ("Malarani", "RM", 5),
        ],
    },
    {
        "name": "Gulmi", "province": "Lumbini", "lat": 28.08, "lng": 83.27, "zone": "hill",
        "munis": [
            ("Resunga", "M", 14),
            ("Musikot", "M", 9),
            ("Isma", "RM", 7),
            ("Chandrakot", "RM", 5),
            ("Satyawati", "RM", 5),
            ("Kaligandaki", "RM", 5),
            ("Gulmi Darbar", "RM", 6),
            ("Madane", "RM", 5),
            ("Malika", "RM", 6),
            ("Chatrakot", "RM", 5),
            ("Dhurkot", "RM", 5),
            ("Ruru", "RM", 6),
        ],
    },
    {
        "name": "Palpa", "province": "Lumbini", "lat": 27.87, "lng": 83.54, "zone": "hill",
        "munis": [
            ("Tansen", "M", 14),
            ("Rampur", "M", 10),
            ("Nisdi", "RM", 6),
            ("Mathagadhi", "RM", 7),
            ("Rainadevi Chhahara", "RM", 7),
            ("Ribdikot", "RM", 5),
            ("Bagnaskali", "RM", 5),
            ("Rambha", "RM", 5),
            ("Tinau", "RM", 7),
            ("Purbakhola", "RM", 5),
        ],
    },
    {
        "name": "Dang", "province": "Lumbini", "lat": 28.10, "lng": 82.30, "zone": "terai",
        "munis": [
            ("Ghorahi", "SMC", 18),
            ("Tulsipur", "SMC", 19),
            ("Lamahi", "M", 9),
            ("Bangalachuli", "RM", 7),
            ("Dangisharan", "RM", 7),
            ("Gadhawa", "RM", 7),
            ("Rajpur", "RM", 5),
            ("Rapti", "RM", 7),
            ("Shantinagar", "RM", 5),
            ("Babai", "RM", 6),
        ],
    },
    {
        "name": "Pyuthan", "province": "Lumbini", "lat": 28.10, "lng": 82.87, "zone": "hill",
        "munis": [
            ("Pyuthan", "M", 10),
            ("Sworgadwary", "M", 10),
            ("Mandavi", "RM", 5),
            ("Mallarani", "RM", 5),
            ("Naubahini", "RM", 5),
            ("Jhimruk", "RM", 5),
            ("Gaumukhi", "RM", 5),
            ("Sarumarani", "RM", 5),
            ("Airawati", "RM", 6),
        ],
    },
    {
        "name": "Rolpa", "province": "Lumbini", "lat": 28.51, "lng": 82.67, "zone": "hill",
        "munis": [
            ("Rolpa", "M", 10),
            ("Triveni", "RM", 5),
            ("Runtigadhi", "RM", 5),
            ("Lungri", "RM", 5),
            ("Sunchhahari", "RM", 5),
            ("Thawang", "RM", 5),
            ("Madi", "RM", 5),
            ("Gangadeva", "RM", 5),
            ("Suwarnabati", "RM", 5),
            ("Paribartan", "RM", 5),
        ],
    },
    {
        "name": "Eastern Rukum", "province": "Lumbini", "lat": 28.60, "lng": 82.63, "zone": "hill",
        "munis": [
            ("Bhume", "RM", 6),
            ("Putha Uttarganga", "RM", 8),
            ("Sisne", "RM", 5),
        ],
    },
    {
        "name": "Banke", "province": "Lumbini", "lat": 28.05, "lng": 81.60, "zone": "terai",
        "munis": [
            ("Nepalgunj", "SMC", 23),
            ("Kohalpur", "M", 15),
            ("Narainapur", "RM", 6),
            ("Rapti Sonari", "RM", 7),
            ("Baijanath", "RM", 6),
            ("Khajura", "RM", 7),
            ("Duduwa", "RM", 6),
            ("Janaki", "RM", 5),
        ],
    },
    {
        "name": "Bardiya", "province": "Lumbini", "lat": 28.25, "lng": 81.37, "zone": "terai",
        "munis": [
            ("Gulariya", "M", 12),
            ("Rajapur", "M", 9),
            ("Madhuwan", "M", 10),
            ("Thakurbaba", "M", 10),
            ("Bansgadhi", "M", 10),
            ("Barbardiya", "M", 10),
            ("Badhaiyatal", "RM", 6),
            ("Geruwa", "RM", 6),
        ],
    },

    # =========================================================================
    # PROVINCE 6 - KARNALI PRADESH  (10 districts)
    # =========================================================================
    {
        "name": "Western Rukum", "province": "Karnali", "lat": 28.63, "lng": 82.37, "zone": "hill",
        "munis": [
            ("Musikot", "M", 12),
            ("Chaurjahari", "M", 10),
            ("Aathbiskot", "M", 9),
            ("Banfikot", "RM", 5),
            ("Triveni", "RM", 5),
            ("Sani Bheri", "RM", 5),
        ],
    },
    {
        "name": "Salyan", "province": "Karnali", "lat": 28.38, "lng": 82.17, "zone": "hill",
        "munis": [
            ("Sharada", "M", 14),
            ("Bangad Kupinde", "M", 9),
            ("Bagchaur", "M", 12),
            ("Kalimati", "RM", 6),
            ("Tribeni", "RM", 5),
            ("Kapurkot", "RM", 7),
            ("Chhatreshwori", "RM", 5),
            ("Kumakh", "RM", 5),
            ("Darma", "RM", 5),
            ("Siddha Kumakh", "RM", 5),
        ],
    },
    {
        "name": "Dolpa", "province": "Karnali", "lat": 29.25, "lng": 82.95, "zone": "mountain",
        "munis": [
            ("Thuli Bheri", "M", 10),
            ("Tripurasundari", "M", 8),
            ("Dolpo Buddha", "RM", 6),
            ("She Phoksundo", "RM", 9),
            ("Jagadulla", "RM", 5),
            ("Mudkechula", "RM", 7),
            ("Kaike", "RM", 5),
            ("Chharka Tangsong", "RM", 5),
        ],
    },
    {
        "name": "Humla", "province": "Karnali", "lat": 30.00, "lng": 81.80, "zone": "mountain",
        "munis": [
            ("Simikot", "RM", 7),
            ("Namkha", "RM", 7),
            ("Kharpunath", "RM", 5),
            ("Sarkegad", "RM", 6),
            ("Chankheli", "RM", 6),
            ("Adanchuli", "RM", 5),
            ("Tanjakot", "RM", 6),
        ],
    },
    {
        "name": "Jumla", "province": "Karnali", "lat": 29.27, "lng": 82.18, "zone": "mountain",
        "munis": [
            ("Chandannath", "M", 9),
            ("Tatopani", "RM", 5),
            ("Patarasi", "RM", 5),
            ("Tila", "RM", 7),
            ("Kanaka Sundari", "RM", 5),
            ("Sinja", "RM", 5),
            ("Hima", "RM", 5),
            ("Guthichaur", "RM", 5),
        ],
    },
    {
        "name": "Kalikot", "province": "Karnali", "lat": 29.15, "lng": 81.62, "zone": "mountain",
        "munis": [
            ("Khandachakra", "M", 11),
            ("Raskot", "M", 10),
            ("Tilagufa", "M", 10),
            ("Pachaljharana", "RM", 5),
            ("Shubha Kalika", "RM", 6),
            ("Sanni Triveni", "RM", 5),
            ("Narharinath", "RM", 6),
            ("Mahawai", "RM", 5),
            ("Palata", "RM", 5),
        ],
    },
    {
        "name": "Mugu", "province": "Karnali", "lat": 29.50, "lng": 82.10, "zone": "mountain",
        "munis": [
            ("Chhayanath Rara", "M", 9),
            ("Mugum Karmarong", "RM", 5),
            ("Soru", "RM", 5),
            ("Khambu", "RM", 5),
        ],
    },
    {
        "name": "Surkhet", "province": "Karnali", "lat": 28.60, "lng": 81.62, "zone": "hill",
        "munis": [
            ("Birendranagar", "M", 14),
            ("Bheriganga", "M", 12),
            ("Gurbhakot", "M", 13),
            ("Panchapuri", "M", 10),
            ("Lekbeshi", "M", 10),
            ("Chaukune", "RM", 5),
            ("Barahatal", "RM", 5),
            ("Chingad", "RM", 5),
            ("Simta", "RM", 5),
        ],
    },
    {
        "name": "Dailekh", "province": "Karnali", "lat": 28.85, "lng": 81.72, "zone": "hill",
        "munis": [
            ("Narayan", "M", 14),
            ("Dullu", "M", 9),
            ("Chamunda Bindrasaini", "M", 10),
            ("Aathbis", "M", 9),
            ("Bhagawatimai", "RM", 7),
            ("Bhairabi", "RM", 8),
            ("Dungeshwar", "RM", 5),
            ("Gurans", "RM", 5),
            ("Mahabu", "RM", 5),
            ("Naumule", "RM", 5),
            ("Thantikandh", "RM", 5),
        ],
    },
    {
        "name": "Jajarkot", "province": "Karnali", "lat": 28.70, "lng": 82.20, "zone": "hill",
        "munis": [
            ("Bheri", "M", 12),
            ("Chhedagad", "M", 10),
            ("Nalgad", "M", 10),
            ("Junichande", "RM", 5),
            ("Kushe", "RM", 5),
            ("Barekot", "RM", 5),
            ("Shivalaya", "RM", 5),
        ],
    },

    # =========================================================================
    # PROVINCE 7 - SUDURPASHCHIM PRADESH  (9 districts)
    # =========================================================================
    {
        "name": "Bajura", "province": "Sudurpashchim", "lat": 29.37, "lng": 81.33, "zone": "mountain",
        "munis": [
            ("Badimalika", "M", 9),
            ("Triveni", "M", 9),
            ("Budhinanda", "M", 9),
            ("Budhiganga", "M", 9),
            ("Gaumul", "RM", 5),
            ("Jagannath", "RM", 5),
            ("Khaptad Chhanna", "RM", 6),
            ("Himali", "RM", 5),
            ("Swamikartik", "RM", 5),
        ],
    },
    {
        "name": "Bajhang", "province": "Sudurpashchim", "lat": 29.53, "lng": 81.18, "zone": "mountain",
        "munis": [
            ("Jayaprithvi", "M", 9),
            ("Bungal", "M", 9),
            ("Talkot", "RM", 6),
            ("Thalara", "RM", 5),
            ("Masta", "RM", 5),
            ("Khaptad Chhededaha", "RM", 5),
            ("Durgathali", "RM", 5),
            ("Kedarsyu", "RM", 5),
            ("Chabispathivera", "RM", 7),
            ("Bitthadchir", "RM", 5),
            ("Surma", "RM", 5),
            ("Saipal", "RM", 5),
        ],
    },
    {
        "name": "Achham", "province": "Sudurpashchim", "lat": 29.04, "lng": 81.25, "zone": "hill",
        "munis": [
            ("Mangalsen", "M", 14),
            ("Kamalbazar", "M", 10),
            ("Sanphebagar", "M", 12),
            ("Panchadewal Binayak", "M", 10),
            ("Bannigadhi Jayagadh", "RM", 5),
            ("Chaurpati", "RM", 5),
            ("Dhakari", "RM", 5),
            ("Mellekh", "RM", 7),
            ("Ramaroshan", "RM", 5),
            ("Turmakhad", "RM", 5),
        ],
    },
    {
        "name": "Doti", "province": "Sudurpashchim", "lat": 29.27, "lng": 80.95, "zone": "hill",
        "munis": [
            ("Dipayal Silgadhi", "M", 14),
            ("Shikhar", "M", 11),
            ("Purbichauki", "RM", 5),
            ("Badikedar", "RM", 5),
            ("Jorayal", "RM", 5),
            ("Sayal", "RM", 5),
            ("Aadarsha", "RM", 6),
            ("K I Singh", "RM", 5),
            ("Bogatan Phudsil", "RM", 5),
        ],
    },
    {
        "name": "Kailali", "province": "Sudurpashchim", "lat": 28.70, "lng": 80.55, "zone": "terai",
        "munis": [
            ("Dhangadhi", "SMC", 19),
            ("Tikapur", "M", 9),
            ("Ghodaghodi", "M", 12),
            ("Lamkichuha", "M", 10),
            ("Bhajani", "M", 9),
            ("Gauriganga", "M", 9),
            ("Godawari", "M", 12),
            ("Bardagoriya", "RM", 5),
            ("Mohanyal", "RM", 5),
            ("Janaki", "RM", 6),
            ("Kailari", "RM", 7),
            ("Joshipur", "RM", 5),
            ("Chure", "RM", 5),
        ],
    },
    {
        "name": "Kanchanpur", "province": "Sudurpashchim", "lat": 28.84, "lng": 80.33, "zone": "terai",
        "munis": [
            ("Bhimdatta", "M", 19),
            ("Punarbas", "M", 11),
            ("Bedkot", "M", 10),
            ("Belauri", "M", 10),
            ("Shuklaphanta", "M", 11),
            ("Krishnapur", "M", 7),
            ("Beldandi", "RM", 5),
            ("Laljhadi", "RM", 5),
            ("Mahakali", "RM", 5),
        ],
    },
    {
        "name": "Dadeldhura", "province": "Sudurpashchim", "lat": 29.30, "lng": 80.58, "zone": "hill",
        "munis": [
            ("Amargadhi", "M", 11),
            ("Parashuram", "M", 12),
            ("Aalitaal", "RM", 5),
            ("Bhageshwar", "RM", 5),
            ("Nawadurga", "RM", 5),
            ("Ajaymeru", "RM", 5),
            ("Ganyapadhura", "RM", 5),
        ],
    },
    {
        "name": "Baitadi", "province": "Sudurpashchim", "lat": 29.57, "lng": 80.35, "zone": "hill",
        "munis": [
            ("Dasharathchand", "M", 11),
            ("Patan", "M", 9),
            ("Melauli", "M", 9),
            ("Purchaudi", "M", 9),
            ("Dogadakedar", "RM", 7),
            ("Dilasaini", "RM", 5),
            ("Pancheshwar", "RM", 7),
            ("Sigas", "RM", 5),
            ("Shivanath", "RM", 5),
            ("Surnaya", "RM", 5),
        ],
    },
    {
        "name": "Darchula", "province": "Sudurpashchim", "lat": 29.85, "lng": 80.55, "zone": "mountain",
        "munis": [
            ("Mahakali", "M", 9),
            ("Shailyashikhar", "M", 9),
            ("Malikarjun", "RM", 6),
            ("Apihimal", "RM", 5),
            ("Duhun", "RM", 5),
            ("Marma", "RM", 5),
            ("Naugad", "RM", 5),
            ("Byans", "RM", 5),
            ("Lekam", "RM", 5),
        ],
    },
]


# ---------------------------------------------------------------------------
# Helper: count totals
# ---------------------------------------------------------------------------
def get_stats():
    """Return summary statistics for the Nepal admin data."""
    total_districts = len(DISTRICTS)
    total_munis = sum(len(d["munis"]) for d in DISTRICTS)
    total_wards = sum(wards for d in DISTRICTS for _, _, wards in d["munis"])
    provinces = set(d["province"] for d in DISTRICTS)
    return {
        "provinces": len(provinces),
        "districts": total_districts,
        "municipalities": total_munis,
        "wards": total_wards,
    }
