# Generated by Django 4.2.28 on 2026-02-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_amenity_propertyrequest_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rental duration in months', null=True),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='move_in_date',
            field=models.DateField(blank=True, help_text='Preferred move-in date (for bookings)', null=True),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='request_type',
            field=models.CharField(choices=[('visit', 'Property Visit'), ('inquiry', 'Rental Inquiry'), ('booking', 'Booking Request')], default='visit', max_length=20),
        ),
    ]
