# Generated by Django 4.2.28 on 2026-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyrequest_add_booking_type_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
