# Generated by Django 4.2 on 2026-07-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_province_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenity_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='government_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='land_tax_receipt',
            field=models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='live_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maximum_occupants',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_rental_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_citizenship',
            field=models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_certificate',
            field=models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_overview',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='recently_inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access_width',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='utility_bill_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
