# Generated by Django 4.2 on 2026-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_amenity_settings_property_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Preferred visit date (for visit requests)', null=True),
        ),
        migrations.AddField(
            model_name='propertyrequest',
            name='visit_time',
            field=models.TimeField(blank=True, help_text='Preferred visit time (for visit requests)', null=True),
        ),
    ]
